### ISSUE TITLE
Two "metrics" - "view logs" navigating to same link for linux integration under Agent details page.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/integrations#881]
**Kibana version:** 7.13.0 Snapshot Kibana cloud environment

**Host OS and Browser version:** Ubuntu 20, All

**Build Details:**
```
  Artifact link used: https://snapshots.elastic.co/7.13.0-ea909f94/downloads/beats/elastic-agent/elastic-agent-7.13.0-SNAPSHOT-linux-x86_64.tar.gz
  Build: 40014
  Commit: 5ea2cf6854c12b9c49217c22f9b5e70668a2379d

```

**Preconditions:**
1. 7.13.0 Snapshot Kibana cloud environment should be available.
2. Linux agent must be installed using default policy having System and Linux integration.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Agent details page
3. Click dropdown icon (>) on "Linux" integration.
4. Observe two "metrics" - "view logs" under Linux integration.

**Note:**
-  Both the options navigate to same location with same results under agent "Logs" tab.

**Expected Result:**
There should be one "metrics" - "view logs" for Linux integration under Agent details page.

**Screenshots:**
![ViewLogs](https://user-images.githubusercontent.com/77374876/113558862-0b6fe580-961e-11eb-944e-e0ff939c1f43.jpg)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @EricDavisX

**Comment by EricDavisX** [comment]
is this Integration side...  @fearful-symmetry is it your ownership for this one/

**Comment by fearful-symmetry** [comment]
It looks like this is related to https://github.com/elastic/package-spec/issues/51, which means the config groups get duplicated like that. Until the underlying issue is fixed, I we don't really have a fix.

**Comment by dikshachauhan-qasource** [comment]
Hi @fearful-symmetry 

Thanks for the update. Please let us know whenever  underlying issue is fixed, so that we can revalidate above reported issue.

Thanks
QAS

**Comment by amolnater-qasource** [comment]
Hi Team
We have revalidated this issue on latest 8.5 SNAPSHOT kibana cloud environment and found it **still reproducible**.
- Two "metrics" columns are displayed for linux integration under Agent details page.

**Build details:**
BUILD: 56489
COMMIT: ac5064b771f6edc2a2ea71da9f68e1afcd08a539

**Screen Recording:**

https://user-images.githubusercontent.com/77374876/191457323-d256ac82-3ad3-411a-9880-0700e12aa1bc.mp4


Please let us know if anything else is required from our end.
Thanks

**Comment by amolnater-qasource** [comment]
FYI @juliaElastic

**Comment by amolnater-qasource** [comment]
Hi Team,
We have revalidated this issue on latest 8.11.0 SNAPSHOT kibana cloud environment and found it **still reproducible**:

**Observations:**
- Two "metrics" columns are displayed for linux integration on Agent details page.


**Screenshot:**
![image](https://github.com/elastic/integrations/assets/77374876/f46c34aa-9c71-462c-b814-0189efb2df12)


**Build details:**
VERSION: 8.11.0 SNAPSHOT
BUILD: 67206
COMMIT: 61bad62aaa322dce11f462ac5f3422f2be3dcd60

Please let us know if anything else is required from our end.

Thanks!

**Comment by amolnater-qasource** [comment]
👍
